### ISSUE TITLE
Calculator Styling Challenge

### ISSUE THREAD

**Issue by dagilleland** [CPSC-1520/DanG-A05-CPSC-1520-Instructor-Workbook-2025-Jan#1]
Part of 005.5 lesson.

![Image](https://github.com/user-attachments/assets/0f7b11e6-a791-4d11-83f4-2b3ecd92c144)

**Comment by dagilleland** [comment]
Here's some starting styles:

```css
#calculator {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 2px;
    background-color: lightslategray;
    max-width: calc(5em * 4);
}

#calculator > output {
    grid-column: 1/5;
    background-color: rgb(10, 10, 102);
    color: lightblue;
    font-size: 2.8em;
    padding: 0 7px;
}

#calculator > button {
    max-width: 5em;
    padding: 1em;
    border: 0;
}

#calculator > button:nth-last-child(3) {
    grid-column: 1 / 3;
    max-width: 10em;
}
```
